In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

from sklearn.metrics import confusion_matrix, accuracy_score, recall_score, f1_score, classification_report

import pandas as pnd


<h1 style="color: red;">Section 1: Data</h1>

<h2>1) Préparation de données</h2>

In [8]:
dataset =pnd.read_csv('diabetes.csv')#import
X = np.array(dataset.drop(columns=['Outcome'])) #features
y = np.array(dataset['Outcome']) #target
#spilt data
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=23)


In [3]:
# 1) Préparation des données
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Charger le dataset
data = pd.read_csv("diabetes.csv")

# Features et target
X = data.drop("Outcome", axis=1)
y = data["Outcome"]

# Normalisation
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Split train/test
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)


<h1 style="color: red;">Section 2: Neural network avec tensorflow</h1>

In [1]:
import tensorflow as tf
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

from tensorflow.keras.optimizers import Adam

<h2>2) Modèle de réseau de neurones</h2>

In [23]:
model_nn = Sequential()
output_layer=Dense(?, input_shape=(X_train.shape[1],), activation='?')
model_nn.add(?)
opt = Adam(learning_rate=?)
model_nn.compile(optimizer=?,loss="?",metrics=["?"])
model_nn.fit(?)

Epoch 1/1000
20/20 [==============================] - 0s 2ms/step - loss: 0.6498 - accuracy: 0.3502
Epoch 2/1000
20/20 [==============================] - 0s 1ms/step - loss: 0.6449 - accuracy: 0.3550
Epoch 3/1000
20/20 [==============================] - 0s 1ms/step - loss: 0.6433 - accuracy: 0.3567
Epoch 4/1000
20/20 [==============================] - 0s 1ms/step - loss: 0.6433 - accuracy: 0.3567
Epoch 5/1000
20/20 [==============================] - 0s 1ms/step - loss: 0.6433 - accuracy: 0.3567
Epoch 6/1000
20/20 [==============================] - 0s 1ms/step - loss: 0.6433 - accuracy: 0.3567
Epoch 7/1000
20/20 [==============================] - 0s 1ms/step - loss: 0.6433 - accuracy: 0.3567
Epoch 8/1000
20/20 [==============================] - 0s 1ms/step - loss: 0.6433 - accuracy: 0.3567
Epoch 9/1000
20/20 [==============================] - 0s 815us/step - loss: 0.6433 - accuracy: 0.3567
Epoch 10/1000
20/20 [==============================] - 0s 1ms/step - loss: 0.5466 - accuracy: 0.44

20/20 [==============================] - 0s 983us/step - loss: 0.3502 - accuracy: 0.6498
Epoch 83/1000
20/20 [==============================] - 0s 1ms/step - loss: 0.3502 - accuracy: 0.6498
Epoch 84/1000
20/20 [==============================] - 0s 711us/step - loss: 0.3502 - accuracy: 0.6498
Epoch 85/1000
20/20 [==============================] - 0s 1ms/step - loss: 0.3502 - accuracy: 0.6498
Epoch 86/1000
20/20 [==============================] - 0s 345us/step - loss: 0.3502 - accuracy: 0.6498
Epoch 87/1000
20/20 [==============================] - 0s 1ms/step - loss: 0.3502 - accuracy: 0.6498
Epoch 88/1000
20/20 [==============================] - 0s 1ms/step - loss: 0.3502 - accuracy: 0.6498
Epoch 89/1000
20/20 [==============================] - 0s 851us/step - loss: 0.3502 - accuracy: 0.6498
Epoch 90/1000
20/20 [==============================] - 0s 2ms/step - loss: 0.3502 - accuracy: 0.6498
Epoch 91/1000
20/20 [==============================] - 0s 902us/step - loss: 0.3502 - accuracy: 0

20/20 [==============================] - 0s 1ms/step - loss: 0.3502 - accuracy: 0.6498
Epoch 243/1000
20/20 [==============================] - 0s 934us/step - loss: 0.3502 - accuracy: 0.6498
Epoch 244/1000
20/20 [==============================] - 0s 2ms/step - loss: 0.3502 - accuracy: 0.6498
Epoch 245/1000
20/20 [==============================] - 0s 650us/step - loss: 0.3502 - accuracy: 0.6498
Epoch 246/1000
20/20 [==============================] - 0s 1ms/step - loss: 0.3502 - accuracy: 0.6498
Epoch 247/1000
20/20 [==============================] - 0s 2ms/step - loss: 0.3502 - accuracy: 0.6498
Epoch 248/1000
20/20 [==============================] - 0s 2ms/step - loss: 0.3502 - accuracy: 0.6498
Epoch 249/1000
20/20 [==============================] - 0s 1ms/step - loss: 0.3502 - accuracy: 0.6498
Epoch 250/1000
20/20 [==============================] - 0s 936us/step - loss: 0.3502 - accuracy: 0.6498
Epoch 251/1000
20/20 [==============================] - 0s 1ms/step - loss: 0.3502 - accura

20/20 [==============================] - 0s 1ms/step - loss: 0.3502 - accuracy: 0.6498
Epoch 403/1000
20/20 [==============================] - 0s 1ms/step - loss: 0.3502 - accuracy: 0.6498
Epoch 404/1000
20/20 [==============================] - 0s 1ms/step - loss: 0.3502 - accuracy: 0.6498
Epoch 405/1000
20/20 [==============================] - 0s 765us/step - loss: 0.3502 - accuracy: 0.6498
Epoch 406/1000
20/20 [==============================] - 0s 920us/step - loss: 0.3502 - accuracy: 0.6498
Epoch 407/1000
20/20 [==============================] - 0s 2ms/step - loss: 0.3502 - accuracy: 0.6498
Epoch 408/1000
20/20 [==============================] - 0s 1ms/step - loss: 0.3502 - accuracy: 0.6498
Epoch 409/1000
20/20 [==============================] - 0s 874us/step - loss: 0.3502 - accuracy: 0.6498
Epoch 410/1000
20/20 [==============================] - 0s 2ms/step - loss: 0.3502 - accuracy: 0.6498
Epoch 411/1000
20/20 [==============================] - 0s 1ms/step - loss: 0.3502 - accura

20/20 [==============================] - 0s 2ms/step - loss: 0.3502 - accuracy: 0.6498
Epoch 563/1000
20/20 [==============================] - 0s 2ms/step - loss: 0.3502 - accuracy: 0.6498
Epoch 564/1000
20/20 [==============================] - 0s 1ms/step - loss: 0.3502 - accuracy: 0.6498
Epoch 565/1000
20/20 [==============================] - 0s 1ms/step - loss: 0.3502 - accuracy: 0.6498
Epoch 566/1000
20/20 [==============================] - 0s 1ms/step - loss: 0.3502 - accuracy: 0.6498
Epoch 567/1000
20/20 [==============================] - 0s 1ms/step - loss: 0.3502 - accuracy: 0.6498
Epoch 568/1000
20/20 [==============================] - 0s 1ms/step - loss: 0.3502 - accuracy: 0.6498
Epoch 569/1000
20/20 [==============================] - 0s 1ms/step - loss: 0.3502 - accuracy: 0.6498
Epoch 570/1000
20/20 [==============================] - 0s 1ms/step - loss: 0.3502 - accuracy: 0.6498
Epoch 571/1000
20/20 [==============================] - 0s 2ms/step - loss: 0.3502 - accuracy: 0.

20/20 [==============================] - 0s 1ms/step - loss: 0.3502 - accuracy: 0.6498
Epoch 723/1000
20/20 [==============================] - 0s 1ms/step - loss: 0.3502 - accuracy: 0.6498
Epoch 724/1000
20/20 [==============================] - 0s 1ms/step - loss: 0.3502 - accuracy: 0.6498
Epoch 725/1000
20/20 [==============================] - 0s 1ms/step - loss: 0.3502 - accuracy: 0.6498
Epoch 726/1000
20/20 [==============================] - 0s 1ms/step - loss: 0.3502 - accuracy: 0.6498
Epoch 727/1000
20/20 [==============================] - 0s 2ms/step - loss: 0.3502 - accuracy: 0.6498
Epoch 728/1000
20/20 [==============================] - 0s 2ms/step - loss: 0.3502 - accuracy: 0.6498
Epoch 729/1000
20/20 [==============================] - 0s 2ms/step - loss: 0.3502 - accuracy: 0.6498
Epoch 730/1000
20/20 [==============================] - 0s 2ms/step - loss: 0.3502 - accuracy: 0.6498
Epoch 731/1000
20/20 [==============================] - 0s 2ms/step - loss: 0.3502 - accuracy: 0.

20/20 [==============================] - 0s 1ms/step - loss: 0.3502 - accuracy: 0.6498
Epoch 883/1000
20/20 [==============================] - 0s 1ms/step - loss: 0.3502 - accuracy: 0.6498
Epoch 884/1000
20/20 [==============================] - 0s 1ms/step - loss: 0.3502 - accuracy: 0.6498
Epoch 885/1000
20/20 [==============================] - 0s 2ms/step - loss: 0.3502 - accuracy: 0.6498
Epoch 886/1000
20/20 [==============================] - 0s 2ms/step - loss: 0.3502 - accuracy: 0.6498
Epoch 887/1000
20/20 [==============================] - 0s 2ms/step - loss: 0.3502 - accuracy: 0.6498
Epoch 888/1000
20/20 [==============================] - 0s 1ms/step - loss: 0.3502 - accuracy: 0.6498
Epoch 889/1000
20/20 [==============================] - 0s 1ms/step - loss: 0.3502 - accuracy: 0.6498
Epoch 890/1000
20/20 [==============================] - 0s 1ms/step - loss: 0.3502 - accuracy: 0.6498
Epoch 891/1000
20/20 [==============================] - 0s 2ms/step - loss: 0.3502 - accuracy: 0.

In [4]:
# 2) Modèle de réseau de neurones
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Input

model_nn = Sequential([
    Input(shape=(X_train.shape[1],)),   # nb de features
    Dense(1, activation='sigmoid')      # sortie binaire
])

# Compilation
model_nn.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Entraînement
history = model_nn.fit(X_train, y_train, epochs=1000, batch_size=16, verbose=1)


Epoch 1/1000
39/39 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.4332 - loss: 0.8695
Epoch 2/1000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.4642 - loss: 0.8387
Epoch 3/1000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4967 - loss: 0.8099
Epoch 4/1000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5212 - loss: 0.7832
Epoch 5/1000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5537 - loss: 0.7591
Epoch 6/1000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5733 - loss: 0.7371
Epoch 7/1000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5912 - loss: 0.7169
Epoch 8/1000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6173 - loss: 0.6982
Epoch 9/1000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6384 - loss: 0.6814
Epoch 10/1000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6515 - loss: 0.6658
Epoch 11/1000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6580 - loss: 0.6520
Epoch 12/1000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step

<h2>3) Prédiction en utilisant le modèle</h2>

In [24]:
yhat_nn=model_nn.predict(X_test)

5/5 [==============================] - 0s 2ms/step


In [25]:
yhat_nn=yhat_nn.flatten()

In [26]:
W_nn, bias_nn = model_nn.layers[0].get_weights()

# Afficher les poids et biais
print("Poids :", W_nn.flatten())
print("Biais :", bias_nn)

Poids : [-1.8824713e-01 -4.6178329e-01 -1.1659192e+00 -4.1882250e-01
 -7.4390217e-04 -6.7114282e-01 -7.7611184e-01 -2.1056099e-01]
Biais : [-1.2246836]


In [27]:
W,bias

(array([ 0.10024915,  0.03641322, -0.01504264,  0.00108397, -0.00118414,
         0.07385572,  0.98318553,  0.0154374 ]),
 -7.835179343769454)

<h2>4) Evaluation du modèle</h2>

In [5]:
# 3) Évaluation
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

y_pred = (model_nn.predict(X_test) > 0.5).astype("int32")

print("Accuracy:", accuracy_score(y_test, y_pred))
print("Matrice de confusion:\n", confusion_matrix(y_test, y_pred))
print("Rapport de classification:\n", classification_report(y_test, y_pred))
#code à fournir

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
Accuracy: 0.7467532467532467
Matrice de confusion:
 [[78 21]
 [18 37]]
Rapport de classification:
               precision    recall  f1-score   support

           0       0.81      0.79      0.80        99
           1       0.64      0.67      0.65        55

    accuracy                           0.75       154
   macro avg       0.73      0.73      0.73       154
weighted avg       0.75      0.75      0.75       154



<h1>From scratch</h1>


<h2>Modèle de régression logistic from scratch avec utilisation des matrices</h2>


In [48]:
learning_rate = 0.0001
epochs = 1000


# Initialisation des paramètres
W = ?  # Shape: (2, 1)
b = 0.0

# Reshape y_train pour garantir les dimensions adéquates 
y_train = y_train.reshape(-1, 1)  # Shape: (n_samples, 1)
n = len(X_train)

# Entraînement (descente de gradient vectorisée)
for epoch in range(epochs):
    y_pred = ? # Shape: (n, 1)
    error = ?  # Shape: (n, 1)

    # Calcul des gradients
    dW = (1/n) * (?)  # Shape: (2, 1)
    db = (1/n) * np.sum(error)        # Scalaire

    # Mise à jour des paramètres
    W -= ?
    b -= learning_rate * db

# Résultats
print("Paramètres ajustés:")
print(f"W = \n{W}")
print(f"b = {b:.4f}")

Paramètres ajustés:
W = 
[[2.55761346]
 [3.19975219]]
b = 0.5860


In [7]:
import numpy as np

# Initialisation
learning_rate = 0.01
epochs = 1000
W = np.zeros((X_train.shape[1], 1))
b = 0.0

y_train = y_train.values.reshape(-1, 1)

def sigmoid(z):
    return 1 / (1 + np.exp(-z))

# Entraînement
for epoch in range(epochs):
    z = X_train @ W + b
    y_pred = sigmoid(z)
    error = y_pred - y_train
    
    dw = (1/len(X_train)) * (X_train.T @ error)
    db = (1/len(X_train)) * np.sum(error)
    
    W -= learning_rate * dw
    b -= learning_rate * db

# Prédictions
y_pred_test = sigmoid(X_test @ W + b)
y_class = (y_pred_test >= 0.5).astype(int)

print("Accuracy (scratch):", accuracy_score(y_test, y_class))
print("Matrice de confusion:\n", confusion_matrix(y_test, y_class))
print("Rapport de classification:\n", classification_report(y_test, y_class))


Accuracy (scratch): 0.7337662337662337
Matrice de confusion:
 [[78 21]
 [20 35]]
Rapport de classification:
               precision    recall  f1-score   support

           0       0.80      0.79      0.79        99
           1       0.62      0.64      0.63        55

    accuracy                           0.73       154
   macro avg       0.71      0.71      0.71       154
weighted avg       0.73      0.73      0.73       154



In [8]:
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression()
clf.fit(X_train, y_train.ravel())

y_pred_sklearn = clf.predict(X_test)

print("Accuracy (sklearn):", accuracy_score(y_test, y_pred_sklearn))
print("Matrice de confusion (sklearn):\n", confusion_matrix(y_test, y_pred_sklearn))


Accuracy (sklearn): 0.7532467532467533
Matrice de confusion (sklearn):
 [[79 20]
 [18 37]]


In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# 1) Préparation des données
data = pd.read_csv("diabetes.csv")
X = data.drop("Outcome", axis=1)
y = data["Outcome"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 2) Modèle de réseau de neurones
model_nn = Sequential([
    Dense(1, input_dim=X_train.shape[1], activation='sigmoid')
])

model_nn.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# 3) Entraînement
history = model_nn.fit(X_train, y_train, epochs=100, verbose=0)

# 4) Évaluation
loss, acc = model_nn.evaluate(X_test, y_test, verbose=0)
print(f"Accuracy (TensorFlow): {acc:.4f}")

# 5) Prédictions
yhat_nn = (model_nn.predict(X_test) > 0.5).astype(int)

print("Matrice de confusion (TensorFlow):\n", confusion_matrix(y_test, yhat_nn))
print("Rapport de classification (TensorFlow):\n", classification_report(y_test, yhat_nn))


C:\Users\k.soumia\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Accuracy (TensorFlow): 0.6364
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step
Matrice de confusion (TensorFlow):
 [[68 31]
 [25 30]]
Rapport de classification (TensorFlow):
               precision    recall  f1-score   support

           0       0.73      0.69      0.71        99
           1       0.49      0.55      0.52        55

    accuracy                           0.64       154
   macro avg       0.61      0.62      0.61       154
weighted avg       0.65      0.64      0.64       154



In [3]:
# Afficher le résumé du modèle
model_nn.summary()


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 1)                   │               9 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 29 (120.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 20 (84.00 B)

La fonction fit() entraîne le modèle en ajustant les poids et biais pour minimiser la fonction de coût. 
Elle prend en entrée les données d'entraînement (X_train, y_train), le nombre d'epochs et renvoie l'historique 
de l'entraînement (valeurs de loss et métriques à chaque epoch).


In [ ]:
Dans ce devoir, nous avons implémenté et comparé plusieurs modèles :

- **Régression linéaire** :
  - Version TensorFlow/Keras : réseau de neurones simple avec 2 entrées et 1 sortie.
  - Version "from scratch" : descente de gradient vectorisée.
  - Version sklearn : validation des résultats.
  → Les trois approches donnent des performances proches (MSE faible, R² élevé).

- **Classification (dataset diabetes)** :
  - Version TensorFlow/Keras : réseau de neurones simple avec fonction d’activation sigmoïde.
  - Version "from scratch" : régression logistique avec descente de gradient.
  - Version sklearn : comparaison avec LogisticRegression.
  → Les résultats montrent une accuracy autour de 0.64–0.75 selon l’approche, avec des différences liées au tuning et à la régularisation.

**En résumé** :  
Ces exercices ont permis de comprendre la logique interne des modèles (calculs matriciels, gradients, mise à jour des paramètres) et de comparer avec les librairies standards. L’évaluation sur training et test set montre l’importance de la généralisation et du tuning pour améliorer les performances.
